format = """
[](#9d7cd8)\
$directory\
[](fg:#9d7cd8 bg:#73daca)\
$git_branch\
[ ](fg:#73daca)\
"""

[directory]
style = "bg:#9d7cd8 fg:#1a1b26"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#73daca fg:#1a1b26"
format = '[ $symbol $branch ]($style)'
