#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

find_repo_root() {
  local current="$1"
  while true; do
    if [[ -f "$current/generator/index.js" && -d "$current/schemas" ]]; then
      printf '%s\n' "$current"
      return 0
    fi
    local parent
    parent="$(dirname "$current")"
    if [[ "$parent" == "$current" ]]; then
      return 1
    fi
    current="$parent"
  done
}

REPO_ROOT="$(find_repo_root "$SKILL_DIR")" || {
  echo "Unable to find repository root from $SKILL_DIR" >&2
  exit 2
}

SCHEMA_SRC="$REPO_ROOT/schemas"
SCHEMA_DST="$SKILL_DIR/schemas"
REF_DIR="$SKILL_DIR/references"
HARNESS_DST="$REPO_ROOT/.agents/skills/kpmg-slidegen"

mkdir -p "$SCHEMA_DST" "$REF_DIR"

cp "$SCHEMA_SRC/contentPack.schema.json" "$SCHEMA_DST/contentPack.schema.json"
cp "$SCHEMA_SRC/deckPlan.schema.json" "$SCHEMA_DST/deckPlan.schema.json"
cp "$SCHEMA_SRC/deckSpec.schema.json" "$SCHEMA_DST/deckSpec.schema.json"
cp "$SCHEMA_SRC/qaReport.schema.json" "$SCHEMA_DST/qaReport.schema.json"

echo "Synced canonical schemas into $SCHEMA_DST"

export SKILL_DIR
node <<'NODE'
import fs from 'node:fs';
import path from 'node:path';

const skillDir = process.env.SKILL_DIR;
if (!skillDir) {
  console.error('SKILL_DIR env var is required');
  process.exit(2);
}

const schemaPath = path.join(skillDir, 'schemas', 'deckSpec.schema.json');
const outPath = path.join(skillDir, 'references', 'slide_types_and_slots.md');
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
const defs = schema.$defs || {};

function resolveRef(slotSchema) {
  if (!slotSchema || typeof slotSchema !== 'object') return null;
  if (!slotSchema.$ref) return slotSchema;
  const ref = String(slotSchema.$ref);
  const defName = ref.split('/').pop();
  return defs[defName] || null;
}

function typeNames(typedDef) {
  const typeDef = typedDef?.properties?.type;
  if (!typeDef || typeof typeDef !== 'object') return [];
  if (typeof typeDef.const === 'string') return [typeDef.const];
  if (Array.isArray(typeDef.enum)) {
    return typeDef.enum.filter((value) => typeof value === 'string');
  }
  return [];
}

const byType = new Map();

for (const [defName, defValue] of Object.entries(defs)) {
  if (!defName.startsWith('slide')) continue;
  if (!Array.isArray(defValue?.allOf) || defValue.allOf.length < 2) continue;

  const typedDef = defValue.allOf[1];
  const names = typeNames(typedDef);
  if (names.length === 0) continue;

  const required = (typedDef.required || []).filter((name) => name !== 'type').sort();
  const minItems = {};

  for (const [slotName, slotSchema] of Object.entries(typedDef.properties || {})) {
    if (slotName === 'type') continue;
    const resolved = resolveRef(slotSchema);
    if (Number.isFinite(resolved?.minItems)) {
      minItems[slotName] = resolved.minItems;
    }
  }

  for (const slideType of names) {
    if (!byType.has(slideType)) {
      byType.set(slideType, { required: new Set(), minItems: {} });
    }
    const entry = byType.get(slideType);
    required.forEach((slot) => entry.required.add(slot));
    Object.assign(entry.minItems, minItems);
  }
}

const rows = [...byType.entries()]
  .map(([slideType, info]) => {
    const required = [...info.required].sort();
    const minItems = Object.entries(info.minItems)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([slot, min]) => `\`${slot}\`>=${min}`)
      .join(', ');

    return {
      slideType,
      required: required.length ? required.map((slot) => `\`${slot}\``).join(', ') : '-',
      minItems: minItems || '-',
    };
  })
  .sort((left, right) => left.slideType.localeCompare(right.slideType));

const lines = [
  '# Slide Types and Slots (Generated)',
  '',
  'This file is generated by `scripts/sync_bundle_from_repo.sh` from `schemas/deckSpec.schema.json`.',
  'Do not edit manually.',
  '',
  `Generated at: ${new Date().toISOString()}`,
  '',
  '| Slide type | Required slots | minItems constraints |',
  '|---|---|---|',
  ...rows.map((row) => `| \`${row.slideType}\` | ${row.required} | ${row.minItems} |`),
  '',
  'Use this sheet for planning/spec authoring sanity checks; schema remains the executable contract.',
  '',
];

fs.writeFileSync(outPath, lines.join('\n'));
console.log(`Generated ${outPath}`);
NODE

if command -v rsync >/dev/null 2>&1; then
  mkdir -p "$HARNESS_DST"
  rsync -a --delete "$SKILL_DIR/" "$HARNESS_DST/"
else
  mkdir -p "$HARNESS_DST"
  find "$HARNESS_DST" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
  cp -R "$SKILL_DIR/." "$HARNESS_DST/"
fi

echo "Synced canonical bundle into $HARNESS_DST"
