#!/usr/bin/env python3
"""Build the single-file Lingo bundle from core modules.

Concatenates `core/formatting.py`, `core/rearrange.py`, and
`core/glossary_generator.py` into `lingo/lingo_bundle.py` while removing
internal imports that are unnecessary once bundled.
"""

from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "core"
LINGO = ROOT / "lingo"
OUTPUT = LINGO / "lingo_bundle.py"

SOURCE_FILES: List[Path] = [
    CORE / "formatting.py",
    CORE / "rearrange.py",
    CORE / "pagination.py",
    CORE / "glossary_generator.py",
]

HEADER = '''"""Single-file bundle for Lingo GPT glossary generation.
AUTO-GENERATED by tools/build_lingo_bundle.py. Do not edit manually.
Source modules: core/formatting.py, core/rearrange.py, core/pagination.py, core/glossary_generator.py

Version: v3 (Adaptive Row Heights)
Frozen: 2025-01-XX
Features:
- Height-based pagination (no text clipping)
- Dynamic row heights for adaptive layouts
- Zero regressions on small/medium glossaries
- Improved large glossary handling (76 fewer clipped terms in 108-term test)
"""
__version__ = "v3"
__template_version__ = "kpmg-glossary-v1"'''


def _strip_internal_imports(text: str) -> str:
    cleaned_lines = []
    skip_depth = 0

    for line in text.splitlines():
        stripped = line.strip()

        if skip_depth:
            skip_depth += line.count("(") - line.count(")")
            continue

        if stripped.startswith("sys.path.insert"):
            continue

        if stripped.startswith("from core.") or stripped.startswith("import core."):
            skip_depth = line.count("(") - line.count(")")
            skip_depth = max(skip_depth, 0)
            continue

        cleaned_lines.append(line)

    return "\n".join(cleaned_lines).rstrip() + "\n"


def build_bundle():
    parts = [HEADER, "# === GENERATED CONTENT BELOW ===\n"]

    for path in SOURCE_FILES:
        content = path.read_text()
        cleaned = _strip_internal_imports(content)
        parts.append(f"# === {path.name} ===\n{cleaned}\n")

    bundle_text = "\n".join(parts)
    compile(bundle_text, str(OUTPUT), "exec")  # fail fast on syntax issues
    OUTPUT.write_text(bundle_text)

    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    print("Included modules:", ", ".join(p.name for p in SOURCE_FILES))


if __name__ == "__main__":
    build_bundle()
